from core.engine import process_query


class ChatService:
    """
    Handles chat-related business logic.
    """

    def stream_response(self, query: str):
        """
        Stream the response generated by the LLM.
        Used by the CLI application.
        """
        return process_query(query)

    async def chat(self, query: str) -> str:
        """
        Generate the complete response.

        Used by the REST API endpoint.
        """

        response = ""

        for chunk in process_query(query):
            response += chunk

        return response