from dataclasses import dataclass

from retrieval.models import SearchResult


@dataclass
class AIResponse:
    """
    Represents the final response generated by the AI.
    """

    answer: str

    sources: list[SearchResult]